# Generated by Django 3.2.16 on 2022-11-19 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=10)),
                ('em1', models.IntegerField(default=0)),
                ('em2', models.IntegerField(default=0)),
                ('em3', models.IntegerField(default=0)),
                ('em4', models.IntegerField(default=0)),
                ('em5', models.IntegerField(default=0)),
                ('em6', models.IntegerField(default=0)),
                ('em7', models.IntegerField(default=0)),
                ('clt1', models.IntegerField(default=0)),
                ('clt2', models.IntegerField(default=0)),
                ('clt3', models.IntegerField(default=0)),
                ('clt4', models.IntegerField(default=0)),
                ('clt5', models.IntegerField(default=0)),
                ('dist1', models.IntegerField(default=0)),
                ('dist2', models.IntegerField(default=0)),
                ('dist3', models.IntegerField(default=0)),
                ('pana1', models.IntegerField(default=0)),
                ('pana2', models.IntegerField(default=0)),
                ('pana3', models.IntegerField(default=0)),
                ('pana4', models.IntegerField(default=0)),
                ('pana5', models.IntegerField(default=0)),
                ('pana6', models.IntegerField(default=0)),
                ('pana7', models.IntegerField(default=0)),
                ('pana8', models.IntegerField(default=0)),
                ('pana9', models.IntegerField(default=0)),
                ('pana10', models.IntegerField(default=0)),
                ('pana11', models.IntegerField(default=0)),
                ('pana12', models.IntegerField(default=0)),
                ('pana13', models.IntegerField(default=0)),
                ('pana14', models.IntegerField(default=0)),
                ('pana15', models.IntegerField(default=0)),
                ('pana16', models.IntegerField(default=0)),
                ('pana17', models.IntegerField(default=0)),
                ('pana18', models.IntegerField(default=0)),
                ('pana19', models.IntegerField(default=0)),
                ('pana20', models.IntegerField(default=0)),
                ('check1', models.IntegerField(default=0)),
                ('check2', models.IntegerField(default=0)),
                ('check3', models.IntegerField(default=0)),
                ('phone', models.CharField(max_length=15)),
                ('Snum', models.CharField(max_length=9)),
                ('Cname', models.CharField(max_length=50)),
                ('starttime', models.DateTimeField(verbose_name='date published')),
                ('endtime', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
